// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var T;

  T = {
    version: 1,
    magic: 0x88892192,
    cipher: {
      key_size: 32,
      iv_size: 8
    },
    hmac: {
      key_size: 32,
      output_size: 32
    },
    defaults: {
      blocksize: 0x100000,
      hashes_per_index_packet: 0x100
    }
  };

  module.exports = T;

}).call(this);
