// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var T;

  T = {
    version: 1,
    cipher: {
      key_size: 32,
      iv_size: 16
    },
    hmac: {
      key_size: 32,
      output_size: 32
    },
    defaults: {
      blocksize: 0x100000
    }
  };

  T.defaults.hashes_per_block = Math.floor((T.defaults.blocksize - 16) / T.hmac.output_size);

  module.exports = T;

}).call(this);
