// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var Stubs;

  exports.Stubs = Stubs = (function() {
    function Stubs() {}

    Stubs.prototype._unimplemented = function(cb) {
      return cb(new Error("unimplemented!"));
    };

    Stubs.prototype.init = function(_arg, cb) {
      var asp;
      asp = _arg.asp;
      return this._unimplemented(cb);
    };

    Stubs.prototype.encrypt_pgp_header = function(_arg, cb) {
      var buf;
      buf = _arg.buf;
      return this._unimplemented(cb);
    };

    Stubs.prototype.decrypt_pgp_header = function(_arg, cb) {
      var buf;
      buf = _arg.buf;
      return this._unimplemented(cb);
    };

    Stubs.prototype.init_aes256ctr = function(_arg, cb) {
      var iv, key;
      key = _arg.key, iv = _arg.iv;
      return this._unimplemented(cb);
    };

    Stubs.prototype.init_hmac_sha256 = function(_arg, cb) {
      var key;
      key = _arg.key;
      return this._unimplemented(cb);
    };

    Stubs.prototype.aes256ctr_encrypt = function(_arg, cb) {
      var buf;
      buf = _arg.buf;
      return this._unimplemented(cb);
    };

    Stubs.prototype.aes256ctr_decrypt = function(_arg, cb) {
      var buf;
      buf = _arg.buf;
      return this._unimplemented(cb);
    };

    Stubs.prototype.hmac_sha256 = function(_arg, cb) {
      var buf;
      buf = _arg.buf;
      return this._unimplemented(cb);
    };

    Stubs.prototype.read = function(_arg, cb) {
      var bytes, start;
      start = _arg.start, bytes = _arg.bytes;
      return this._unimplemented(cb);
    };

    Stubs.prototype.write = function(_arg, cb) {
      var buf, start;
      buf = _arg.buf, start = _arg.start;
      return this._unimplemented(cb);
    };

    Stubs.prototype.prng = function(n, cb) {
      return this._unimplemented(cb);
    };

    Stubs.prototype.close = function(cb) {
      return this._unimplemented(cb);
    };

    Stubs.prototype.estimate_pgp_header_length = function(cb) {
      return this._unimplemented(cb);
    };

    return Stubs;

  })();

}).call(this);
